### ISSUE TITLE
Reopening of issue #2 - Tags no longer applying

### ISSUE THREAD

**Issue by patpicos** [prombouts/vsts-auto-tagging#3]
Hi Peter, my previous comment should read
Now im getting no tags applied

This is worse than before..need to reopen the issue
```
2018-10-05T12:48:23.9886464Z Writing 0 tags to resource /subscriptions/***********-9a84-b0d5f05f83c7/resource
```

**Comment by prombouts** [comment]
Hi patpicos,

I've just pushed a new version; tested on both existing and new tags on both resource groups and resources within groups. Should be working now.
